<?php
$layout->helper->addHeadCssFile('css/style.css');
$layout->helper->addHeadCssFile('css/topmenu.css');
$layout->helper->addHeadCssFile('css/persontree.css');
$layout->helper->addHeadJsFile('js/jquery.js');
?>
<!DOCTYPE html>

<html>

<head>
    <?php
    $layout->helper->getHeadJs();
    $layout->helper->getHeadCss();
    ?>
    <link href="http://fonts.googleapis.com/css?family=Roboto+Condensed:400,700" rel="stylesheet" type="text/css">
</head>

<body>

	<header>
		<div class="container">
			<div class="welcome">
				<h1>MultiLevelTree</h1>
				<h2><?= $layout->_('Prezentacja drzewa')?></h2>
			</div>
			
			<div class="rightColumn">
    			
                <div class="jobInfo">
                    <label>Router::getRouting() &amp; Router::getParams()</label>
    				<div class="element">
    					<label>Module</label><span><?= MKFramework\Director::getModuleName(); ?></span>
    				</div>
    				<div class="element">
    					<label>Controller</label><span><?= MKFramework\Director::getControllerName(); ?></span>
    				</div>
    				<div class="element">
    					<label>Job</label><span><?= MKFramework\Director::getJobName(); ?></span>
    				</div>
    				<div class="element">
    					<label>Params</label><span><?php echo http_build_query (MKFramework\Director::getRouter()->getParams()); ?></span>
    				</div>
    
    
    		      </div>
		      
		      </div>

		</div>

	</header>


	<div class="mainMenu">
		<div class="container">
	       <?= $layout->mainMenu; ?>
	    </div>
	</div>


	<div class="content" style="">





		<div class="container">
			<div class="jobOutput">    
                <?php echo $layout->getViewContent(); ?>
            </div>
		</div>


	</div>






</body>

</html>