<?php
$layout->helper->addHeadCssFile('css/style.css');
$layout->helper->addHeadJsFile('js/jquery.js');
?>
<!DOCTYPE html>

<html>

<head>
    <?php
    $layout->helper->getHeadJs();
    $layout->helper->getHeadCss();
    ?>
</head>

<body>

	<header> NESSUN FRAMEWORK - default layout START - (c) by <?php echo $layout->_('Marcin'); ?></header>

	<div class="mainMenu">
	   <?= $layout->mainMenu; ?>
	</div>

	<div class="jobInfo">
		job output: Module: <B><?= MKFramework\Director::getModuleName(); ?></B>
		| Controller: <B><?= MKFramework\Director::getControllerName(); ?></B>
		| Job: <B><?= MKFramework\Director::getJobName(); ?></B> | Params: <B><?php echo http_build_query (MKFramework\Director::getRouter()->getParams()); ?></B>


	</div>

	<div class="jobOutput">    
        <?php echo $layout->getViewContent(); ?>
    </div>




	<footer> NESSUN FRAMEWORK - default layout END 
	
	<div class="bottomMenu">
	
	   <a href="<?= $layout->helper->getUrl(array('module' => 'tools')); ?>">link do TOOLS</a>
	
	</div>
	
	</footer>


</body>

</html>