<h1>
    Autor - Marcin Klimczuk
</h1>


<h2>Umiejętności</h2>

<label>Backend</label>
<ul>
<li>OOP&amp;D PHP
<li>MySQL
<li>Wzorzec MVC - <a href="https://github.com/motarny/MKFramework" target=_blank>mój eksperymentalny framework</a>
<li>Popularne wzorce projektowe (Singleton, Fabryka, Rejestr...)
<li>Zend Framework
<li>Doctrine 2
</ul>

<label>Frontend</label>
<ul>
<li>HTML + CSS, RWD
<li>JS + jQuery, Ajax
<li>Photoshop
</ul>

<label>Inne</label>
<ul>
<li>Podstawy Linux (instalacja, konfiguracja LAMP, domeny)
<BR>
(Ta aplikacja stoi na samodzielnie skonfigurowanym od "gołego" systemie.)
<li>Znajomość Git
<li>Używam Eclipse PDT (wcześniej trochę phpStorm, póki trial trwał :) 
</ul>

<label>W planie</label>
<ul>
<li>Doctrine 2 ORM głębiej
<li>TDD w praktyce
<li>Certyfikat ZCE
<li>Więcej wzorców projektowych
<li>Zend Framework 2 głębiej
</ul>


<h2>Kontakt</h2>

<ul>
<li>e-mail: marcin@klimczuk.info
<li>tel. +48 603 133 623
<li>GitHub: <a href="https://github.com/motarny" target="_blank">motarny</a>
</ul>