
<!DOCTYPE html>

<html>

<head>
    <link rel="stylesheet" type="text/css" href="css/style.css">
</head>

<body>

    <header>
        MKF MultiLevelTree TOOLS
    </header>

    
    <div class="jobInfo">
        job output:  
        Module: <B><?= MKFramework\Director::getModuleName(); ?></B> | 
        Controller: <B><?= MKFramework\Director::getControllerName(); ?></B> | 
        Job: <B><?= MKFramework\Director::getJobName(); ?></B>
    
    </div>
    
    <div class="jobOutput">    
        <?php echo $layout->getViewContent(); ?>
    </div>

   

</body>

</html>