<?php

// z roota
$layout->helper->addHeadCssFile('css/style.css', false);
$layout->helper->addHeadCssFile('css/topmenu.css',false);
$layout->helper->addHeadCssFile('css/styletools.css');       // nadpisuje pare styli
$layout->helper->addHeadJsFile('js/jquery.js', false);

?>

<!DOCTYPE html>

<html>

<head>
    <?php
    $layout->helper->getHeadJs();
    $layout->helper->getHeadCss();
    ?>
</head>

<body>

	<header>
		<div class="container">
			<div class="welcome">
				<h1>MultiLevelTree TOOLS</h1>
				<h2><?= $layout->_('Zestaw narzędzi do Multi Level Tree')?></h2>
			</div>
			
			<div class="rightColumn">
    			
                <div class="jobInfo">
                    <label>Router::getRouting() &amp; Router::getParams()</label>
    				<div class="element">
    					<label>Module</label><span><?= MKFramework\Director::getModuleName(); ?></span>
    				</div>
    				<div class="element">
    					<label>Controller</label><span><?= MKFramework\Director::getControllerName(); ?></span>
    				</div>
    				<div class="element">
    					<label>Job</label><span><?= MKFramework\Director::getJobName(); ?></span>
    				</div>
    				<div class="element">
    					<label>Params</label><span><?php echo http_build_query (MKFramework\Director::getRouter()->getParams()); ?></span>
    				</div>
    
    
    		      </div>
		      
		      </div>

		</div>

	</header>


	<div class="mainMenu">
		<div class="container">
	       <?= $layout->mainMenu; ?>
	    </div>
	</div>

	<div class="jobOutput">    
        <?php echo $layout->getViewContent(); ?>
    </div>



</body>

</html>