<div class="personInfo">



</div>

<div class="personTree">

    <?php
    foreach ($v->personsTree as $person) {
        $personLink = $view->helper->getUrl(array(
            'module' => 'default',
            'controller' => 'person',
            'job' => 'show',
            'params' => array ('personid' => $person['PersonId'])
        )
        );
        
        ?>
            <div class="person" style="margin-left:<?= $person['poziom'] * 40 - 40 ?>px;">
		<div class="name">
			<span class="level" style="font-size: 11px">poziom: <B><?= $person['poziom'] ?></B></span>
			<span class="name"><a href="<?= $personLink ?>"><?php echo $person['Name'] . ' ' . $person['Surname'] ?></a></span>
            <span class="personid"><?= '&nbsp;&nbsp;' . $person['PersonId'] ?></span>
            <div class="uptree"><?php echo $person['sciezka'] ?></div>
		</div>
	</div>
            <?php
    }
    
    // echo json_encode($v->personsTree);
    
    ?>

</div>