
INDEX Person Info

<div class="personTree">

    <?php
     
        foreach ($v->personsTree as $person)
        {
            ?>
            <div class="person" style="margin-left:<?= $person['poziom'] * 40 - 40 ?>px;">
            <div class="name">
                <span class="level" style="font-size:11px">poziom: <B><?= $person['poziom'] ?></B></span>
                <?php echo $person['Name'] . ' ' . $person['Surname'] . ' [id: <B>' . $person['PersonId'] . '</B>]'?></div>
                <div class="uptree"><?php echo $person['sciezka'] ?></div>
            </div>
            <?php 
        }
        
        
    
        //echo json_encode($v->personsTree);
    
    
    ?>

</div>